"use strict";

const pluginName = "weapp2";
const sharedIgnorePatterns = ["**/miniprogram_npm/*", "**/@babel/*"];
const sharedEnv = {
  browser: true,
  node: true,
  es2021: true,
  commonjs: true,
};
const weappGlobals = {
  wx: "readonly",
  App: "readonly",
  Page: "readonly",
  getCurrentPages: "readonly",
  getApp: "readonly",
  Component: "readonly",
  Behavior: "readonly",
  requirePlugin: "readonly",
  requireMiniProgram: "readonly",
  __wxConfig: "readonly",
  define: "readonly",
  globalThis: "readonly",
};
const wxsGlobals = {
  console: "readonly",
  Date: "readonly",
  decodeURI: "readonly",
  decodeURIComponent: "readonly",
  encodeURI: "readonly",
  encodeURIComponent: "readonly",
  getDate: "readonly",
  getRegExp: "readonly",
  Infinity: "readonly",
  isFinite: "readonly",
  isNaN: "readonly",
  JSON: "readonly",
  Math: "readonly",
  module: "readonly",
  NaN: "readonly",
  Number: "readonly",
  parseFloat: "readonly",
  parseInt: "readonly",
  require: "readonly",
  undefined: "readonly",

  Array: "off",
  Boolean: "off",
  Error: "off",
  EvalError: "off",
  eval: "off",
  exports: "off",
  escape: "off",
  Function: "off",
  global: "off",
  Object: "off",
  RangeError: "off",
  ReferenceError: "off",
  RegExp: "off",
  String: "off",
  SyntaxError: "off",
  TypeError: "off",
  URIError: "off",
  unescape: "off",
};
const legacyWeappGlobals = Object.fromEntries(
  Object.keys(weappGlobals).map((key) => [key, true]),
);
const sharedRules = {
  "weapp2/component": "error",
  "weapp2/import": "error",
  "weapp2/wx-navigate": "error",

  "no-unused-vars": "off",
  "no-empty": "off",
  "no-async-promise-executor": "off",
  "no-useless-catch": "off",
  "no-useless-escape": "off",
  "no-redeclare": "warn",
  "no-case-declarations": "warn",
  "no-unreachable": "warn",
  "no-constant-condition": "warn",
  "no-mixed-spaces-and-tabs": "off",
  "no-cond-assign": "warn",
  "no-control-regex": "off",
  "no-extra-semi": "warn",
  "no-dupe-else-if": "warn",
  "no-irregular-whitespace": "warn",
  "no-extra-boolean-cast": "warn",
  "no-prototype-builtins": "warn",
  "no-self-assign": "warn",
  "no-inner-declarations": "warn",
  "no-dupe-keys": "warn",
  "no-empty-pattern": "warn",
  "no-unsafe-negation": "warn",
  "no-shadow-restricted-names": "warn",
  "no-unexpected-multiline": "warn",
  "no-fallthrough": "warn",
  "no-regex-spaces": "warn",
  "no-unused-labels": "warn",
  "no-duplicate-case": "warn",
  "use-isnan": "warn",
};
module.exports = {
  legacyWeappGlobals,
  pluginName,
  sharedEnv,
  sharedIgnorePatterns,
  sharedRules,
  weappGlobals,
  wxsGlobals,
};
